server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/auth_db}
    username: ${AUTH_DB_USERNAME:user}
    password: ${AUTH_DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cloud:
    openfeign:
      client:
        config:
          user-service:
            connectTimeout: 2000
            readTimeout: 2000

logging:
  level:
    root: info

  masking:
    mask: "***"

    fullMaskingJsonBodyPaths:
      - password
      - token
      - accessToken

    partialMaskingJsonBodyPaths:
      - email

    maskHeaders:
      - Authorization

    partialMaskPercents: 0.6
    minLengthForPartialMasking: 3

security:
  internal:
    token: ${INTERNAL_SERVICE_TOKEN:super-secret}
  jwt:
    secret: ${JWT_SECRET:super-secret-key-super-secret-key-super-secret-key-123}
    access-token-expiration: 900        # 15 мин
    refresh-token-expiration: 43200     # 12 часов

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8082}

user-sync:
  retry-delay-ms: ${USER_SYNC_RETRY_DELAY_MS:3600000}
  initial-delay-ms: ${USER_SYNC_INITIAL_DELAY_MS:60000}

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
